{% set version = "0.5.0" %}

package:
  name: muq
  version: {{ version }}

source:
  url: https://github.com/NexGenAnalytics/MIT-MUQ/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 309174667814bade37a5b826d08444411b25b0dfc53e98c7350670d90d153568

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - numpy
    - hdf5
    - libboost-devel
    - eigen >=3.3
    - sundials >=5.5.0,<6
    - nanoflann ==1.5.5
    - nlopt
  run:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - libboost-devel
    - eigen >=3.3
    - sundials >=5.5.0,<6
    - nanoflann ==1.5.5
    - nlopt

test:
  imports:
    - muq.Approximation
    - muq.Modeling
    - muq.Optimization
    - muq.SamplingAlgorithms
    - muq.Utilities

about:
  home: http://muq.mit.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: 'A suite of uncertainty quantification and phyiscal-statistical modeling tools.'
  description: 'MUQ is a c++ library with python wrapper that contains tools for constructing models involving a mix of statistical and physical components.  It also contains a suite of uncertainty quantification tools including MCMC, polynomial chaos, Gaussian processes, Karhunen Loeve expansions, and transport maps.'
  doc_url: http://muq.mit.edu/master-muq2-docs/
  dev_url: https://bitbucket.org/mituq/muq2/src/master/

extra:
  recipe-maintainers:
    - linusseelinger
    - mparno
