{% set version = "0.4.5" %}

package:
  name: muq
  version: {{ version }}

source:
  url: https://bitbucket.org/mituq/muq2/downloads/muq_{{ version | replace(".", "_") }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - numpy
    - hdf5
    - boost-cpp
    - eigen >=3.3
    - sundials >=5.4.0,<6
    - nanoflann ==1.3.1
    - nlopt
  run:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5
    - boost-cpp
    - eigen >=3.3
    - sundials >=5.4.0,<6
    - nanoflann ==1.3.1
    - nlopt

test:
  imports:
    - muq.Approximation
    - muq.Modeling
    - muq.Optimization
    - muq.SamplingAlgorithms
    - muq.Utilities

about:
  home: http://muq.mit.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  summary: 'A suite of uncertainty quantification and phyiscal-statistical modeling tools.'
  description: 'MUQ is a c++ library with python wrapper that contains tools for constructing models involving a mix of statistical and physical components.  It also contains a suite of uncertainty quantification tools including MCMC, polynomial chaos, Gaussian processes, Karhunen Loeve expansions, and transport maps.'
  doc_url: http://muq.mit.edu/master-muq2-docs/
  dev_url: https://bitbucket.org/mituq/muq2/src/master/

extra:
  recipe-maintainers:
    - linusseelinger
    - mparno
